apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - rbac.yaml

namespace: monitoring

patches:
  - path: patch-statefulset.yaml

replicas:
  - name: vector-aggregator
    count: 3

images:
  - name: timberio/vector
    newTag: 0.45.0-distroless-libc

labels:
  - pairs:
      app.kubernetes.io/app: vector-aggregator
      app.kubernetes.io/version: 0.45.0-distroless-libc
      app.kubernetes.io/component: aggregator
      app.kubernetes.io/environment: development
      vector.dev/exclude: "true"
    includeSelectors: true # <-- false by default
    includeTemplates: true # <-- false by default

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: vector-aggregator-extra-env
    envs:
      - files/vector-aggregator-extra-env
  - name: vector-aggregator-config
    files:
      - vector-aggregator.yaml=files/vector-aggregator.yaml
