apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vector-aggregator
spec:
  template:
    spec:
      containers:
        - name: vector-aggregator
          envFrom:
            - secretRef:
                name: vector-aggregator-extra-env
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1.5"
              memory: "1.5Gi"
          volumeMounts:
            - name: vector-aggregator-config
              mountPath: "/etc/vector/vector-aggregator.yaml"
              subPath: "vector-aggregator.yaml"
              readOnly: true
      volumes:
        - name: vector-aggregator-config
          secret:
            secretName: vector-aggregator-config
