apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_KRAFT_MODE: 'true'
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
  KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
  KAFKA_DEFAULT_REPLICATION_FACTOR: '3'
  KAFKA_MIN_INSYNC_REPLICAS: '2'
  KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT
  KAFKA_LOG_DIRS: /var/lib/kafka/data
  KAFKA_SASL_MECHANISMS: PLAIN
  KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
  KAFKA_SASL_USER: admin
  KAFKA_SASL_PASSWORD: admin
  KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
