apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  clusterIP: none
  ports:
    - name: broker
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: controller
      port: 9093
      protocol: TCP
      targetPort: 9093
