apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  template:
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.9.0
          ports:
            - name: broker
              containerPort: 9092
              protocol: TCP
            - name: controller
              containerPort: 9093
              protocol: TCP
          envFrom:
            - configMapRef:
                name: kafka-config
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAFKA_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "SASL_PLAINTEXT://$(POD_NAME).kafka.$(POD_NAMESPACE).svc.cluster.local:9093"
            - name: KAFKA_SUPER_USERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_SASL_USER
            - name: KAFKA_SASL_JAAS_CONFIG
              value: |
                org.apache.kafka.common.security.plain.PlainLoginModule required
                username="$(KAFKA_SASL_USER)"
                password="$(KAFKA_SASL_PASSWORD)"
                user_$(KAFKA_SASL_USER)="$(KAFKA_SASL_PASSWORD)";
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
