apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vector-aggregator
spec:
  replicas: 3  # Scale thành 3 instance
  podManagementPolicy: OrderedReady
  minReadySeconds: 0
  serviceName: vector-aggregator-headless
  template:
    spec:
      serviceAccountName: vector
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 60
      containers:
        - name: vector-aggregator
          image: timberio/vector:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: vector-aggregator-extra-env
          ports:
            - name: vector
              containerPort: 9090
              protocol: TCP
            - name: vector-api
              containerPort: 8686
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1.5"
              memory: "1.5Gi"
          volumeMounts:
            - name: vector-aggregator-config
              mountPath: "/etc/vector/vector-aggregator.yaml"
              subPath: "vector-aggregator.yaml"
              readOnly: true
      volumes:
        - name: vector-aggregator-config
          secret:
            secretName: vector-aggregator-config
