apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - rbac.yaml

namespace: dev

patches:
  - path: patch-deployment.yaml

replicas:
  - name: kubehelper
    count: 1

images:
  - name: myregistry/kubehelper
    newTag: v1

labels:
  - pairs:
      app: kubehelper
      environment: development
    includeSelectors: true # <-- false by default
    includeTemplates: true # <-- false by default

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: kubehelper-extra-env
    behavior: create
    envs:
      - files/kubehelper-extra-env
