apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubehelper

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubehelper
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "get","list" ]
  - nonResourceURLs: [ "*" ]
    verbs: [ "get","list" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubehelper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubehelper
subjects:
  - kind: ServiceAccount
    name: kubehelper
    namespace: dev
