apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
spec:
  template:
    spec:
      containers:
        - name: opensearch
          volumeMounts:
            - name: opensearch-config
              mountPath: /usr/share/opensearch/config/opensearch.yml
              subPath: opensearch.yml
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
      volumes:
        - name: opensearch-config
          configMap:
            name: opensearch-config
  volumeClaimTemplates:
    - metadata:
        name: opensearch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
