apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
data:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0
    discovery.seed_hosts: ["opensearch-0", "opensearch-1", "opensearch-2"]
    cluster.initial_master_nodes: ["opensearch-0", "opensearch-1", "opensearch-2"]
