apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
spec:
  template:
    spec:
      containers:
        - name: kafka-exporter
          image: myregistry/kafka-exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: exporter
              containerPort: 9308
              protocol: TCP
