apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    isDefault: true
    access: proxy
    url: http://PROMETHEUS_IP:PROMETHEUS_PORT/
    # url: http://prometheus-server.monitoring.svc.cluster.local:9090/
