apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-alertmanager-data
spec:
  storageClassName: nfs-subdir-external-sc-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
spec:
  storageClassName: nfs-subdir-external-sc-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
