apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  revisionHistoryLimit: 0
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
  template:
    spec:
      serviceAccountName: grafana
      enableServiceLinks: false
      imagePullSecrets:
        - name: secret_pull
      nodeSelector:
        label: value
      securityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsUser: 472
      volumes:
        - name: grafana-ini
          secret:
            secretName: grafana-ini
        - name: grafana-datasources
          secret:
            secretName: grafana-datasources
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
      containers:
        - name: grafana
          envFrom:
            - configMapRef:
                name: grafana-extra-env
          securityContext:
            runAsNonRoot: true
            runAsUser: 472
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
          livenessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 30
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
          volumeMounts:
            - name: grafana-ini
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
            - name: grafana-data
              mountPath: /var/lib/grafana
