apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  storageClassName: nfs-subdir-external-sc-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
