apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - rbac.yaml

namespace: monitoring

patches:
  - path: patch-daemonset.yaml

images:
  - name: timberio/vector
    newTag: 0.45.0-distroless-libc

labels:
  - pairs:
      app.kubernetes.io/app: vector-agent
      app.kubernetes.io/version: 0.45.0-distroless-libc
      app.kubernetes.io/component: agent
      app.kubernetes.io/environment: dev
      vector.dev/exclude: "true"
    includeSelectors: true # <-- false by default
    includeTemplates: true # <-- false by default

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: vector-agent-extra-env
    envs:
      - files/vector-agent-extra-env
  - name: vector-agent-config
    files:
      - vector-agent.yaml=files/vector-agent.yaml
