apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager
spec:
  ports:
    - name: alertmanager
      port: 9093
      protocol: TCP
      targetPort: 9093
    - name: meshpeer
      port: 6783
      protocol: TCP
      targetPort: 6783

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
spec:
  ports:
    - name: pushgateway
      port: 9091
      protocol: TCP
      targetPort: 9091

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
spec:
  ports:
    - name: prometheus
      port: 9090
      protocol: TCP
      targetPort: 9090
