apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

patches:
  - path: patch-deployment.yaml

replicas:
  - name: kafka-ui
    count: 1

images:
  - name: myregistry/kafka-ui
    newTag: v1

labels:
  - pairs:
      app: kafka-ui
      environment: development
    includeSelectors: true # <-- false by default
    includeTemplates: true # <-- false by default

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: kafka-ui-extra-env
    behavior: create
    envs:
      - files/kafka-ui-extra-env
  - name: kafka-ui-config
    behavior: create
    files:
      - kafka-ui-config.yaml=files/kafka-ui-config.yaml
