apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  labels:
    app.kubernetes.io/authority: MSP-Plus
spec:
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
  template:
    spec:
      enableServiceLinks: false
      imagePullSecrets:
        - name: secret_pull
      nodeSelector:
        label: value
      volumes:
        - name: kafka-ui-config
          configMap:
            name: kafka-ui-config
      containers:
        - name: kafka-ui
          envFrom:
            - secretRef:
                name: kafka-ui-extra-env
          volumeMounts:
            - name: kafka-ui-config
              mountPath: /etc/kafka-ui/config/kafka-ui-config.yaml
              subPath: kafka-ui-config.yaml
