apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

patches:
  - path: patch-deployment.yaml

replicas:
  - name: kube-state-metrics
    count: 1

images:
  - name: myregistry/kube-state-metrics
    newTag: "2.14.0"

labels:
  - pairs:
      app: kube-state-metrics
      environment: development
    includeSelectors: true # <-- false by default
    includeTemplates: true # <-- false by default

commonAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: '8080'
  prometheus.io/scrape: 'true'

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: kube-state-metrics-kubeconfig
    behavior: create
    files:
      - kubeconfig=files/kubeconfig
