apiVersion: apps/v1
kind: Deployment
metadata:
  name: webkubectl
spec:
  template:
    spec:
      containers:
        - name: webkubectl
          image: myregistry/webkubectl:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: webkubectl
              containerPort: 8080
              protocol: TCP
          securityContext:
            privileged: true
