apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - name: grafana
      port: 3000
      protocol: TCP
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-image-renderer
spec:
  ports:
    - name: renderer
      port: 8081
      protocol: TCP
      targetPort: 8081
