apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

replicas:
- name: cloudbeaver
  count: 1

images:
  - name: dbeaver/cloudbeaver
    newTag: latest

labels:
  - pairs:
      app: cloudbeaver
      environment: development
    includeSelectors: true # <-- false by default
    includeTemplates: true # <-- false by default

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: cloudbeaver-config
    files:
      - cloudbeaver.conf=files/cloudbeaver.conf
      - data-sources.json=files/data-sources.json
      - initial-data.conf=files/initial-data.conf
