apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - rbac.yaml

namespace: dev

patches:
  - path: patch-deployment.yaml

replicas:
  - name: kafka-exporter
    count: 1

images:
  - name: myregistry/kafka-exporter
    newTag: v1.7.0

labels:
  - pairs:
      app: kafka-exporter
      environment: development
    includeSelectors: true # <-- false by default
    includeTemplates: true # <-- false by default

commonAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: '9308'
  prometheus.io/scrape: 'true'

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: kafka-exporter-extra-env
    behavior: create
    envs:
      - files/kafka-exporter-extra-env
