apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-exporter

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-exporter

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kafka-exporter
subjects:
  - kind: ServiceAccount
    name: kafka-exporter
    namespace: dev
