apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

patches:
  - path: patch-daemonset.yaml

images:
  - name: elastic/filebeat
    newTag: "7.17.24"

labels:
  - pairs:
      app: filebeat
      environment: development
    includeSelectors: true # <-- false by default
    includeTemplates: true # <-- false by default

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: filebeat-config
    behavior: create
    files:
      - filebeat.yml=files/filebeat.yml
