apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-agent
spec:
  minReadySeconds: 0
  template:
    spec:
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 60
      containers:
        - name: vector-agent
          image: timberio/vector:latest
          imagePullPolicy: IfNotPresent
          args:
            - --config-dir=${VECTOR_CONFIG_DIR}
            - --config=${VECTOR_CONFIG}
          env:
            - name: PROCFS_ROOT
              value: "/host/proc"
            - name: SYSFS_ROOT
              value: "/host/sys"
            - name: VECTOR_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
          #   - name: vector
          #     containerPort: 6000
          #     protocol: TCP
            - name: vector-api
              containerPort: 8686
              protocol: TCP
          #   - name: vector-http
          #     containerPort: 9000
          #     protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8686
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8686
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: var-log
              mountPath: /var/log/
              readOnly: true
            - name: var-lib
              mountPath: /var/lib
              readOnly: true
            - name: procfs
              mountPath: /host/proc
              readOnly: true
            - name: sysfs
              mountPath: /host/sys
              readOnly: true
      volumes:
        - name: var-log
          hostPath:
            path: /var/log/
        - name: var-lib
          hostPath:
            path: /var/lib/
        - name: procfs
          hostPath:
            path: /proc
        - name: sysfs
          hostPath:
            path: /sys
