apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  template:
    spec:
      containers:
        - name: kibana
          image: myregistry/kibana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: kibana
              containerPort: 5601
              protocol: TCP
