---
apiVersion: v1
kind: Service
metadata:
  name: vector-aggregator
spec:
  type: ClusterIP
  ports:
    - name: vector
      port: 6000
      protocol: TCP
    - name: vector-api
      port: 8686
      protocol: TCP
    - name: vector-http
      port: 9000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: vector-aggregator-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: vector
      port: 6000
      protocol: TCP
    - name: vector-api
      port: 8686
      protocol: TCP
    - name: vector-http
      port: 9000
      protocol: TCP
