apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vector-aggregator
spec:
  podManagementPolicy: OrderedReady
  minReadySeconds: 0
  serviceName: vector-aggregator-headless
  template:
    spec:
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 60
      containers:
        - name: vector-aggregator
          image: timberio/vector:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: vector
              containerPort: 6000
              protocol: TCP
            - name: vector-api
              containerPort: 8686
              protocol: TCP
            - name: vector-http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8686
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8686
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
  # volumeClaimTemplates:
