apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
spec:
  template:
    spec:
      containers:
        - name: cloudbeaver
          image: dbeaver/cloudbeaver:latest
          ports:
            - name: cloudbeaver
              containerPort: 8978
