apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pvc.yaml

namespace: dev

patches:
  - path: patch-deployment.yaml

replicas:
  - name: filebrowser
    count: 1

images:
  - name: myregistry/filebrowser
    newTag: v1

labels:
  - pairs:
      app: filebrowser
      environment: development
    includeSelectors: true # <-- false by default
    includeTemplates: true # <-- false by default

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: filebrowser-config
    behavior: create
    files:
      - filebrowser.json=files/filebrowser.json
