apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data
spec:
  storageClassName: nfs-subdir-external-sc-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
