# ---------------------------------- CONFIGS ---------------------------------- #
logging.level: error

# ---------------------------------- INPUT ---------------------------------- #
filebeat.inputs:
  #  System logs
  - type: log
    paths:
      - /var/log/syslog
      - /var/log/auth.log

  # NGINX: access logs
  - type: container
    multiline.pattern: '^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}'
    multiline.negate: true
    multiline.match: after
    paths:
      - /var/log/containers/*.log
    processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

# ---------------------------------- OUTPUT ---------------------------------- #
output.logstash:
  hosts: ["LOGSTASH_IP:5044"]
