apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

replicas:
- name: pgbouncer
  count: 1

images:
  - name: bitnami/pgbouncer
    newTag: "1.24.0"

labels:
  - pairs:
      app: pgbouncer
      environment: development
    includeSelectors: true # <-- false by default
    includeTemplates: true # <-- false by default

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: pgbouncer-config
    files:
      - pgbouncer.ini=files/pgbouncer.ini
      - userlist.txt=files/userlist.txt
