apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  ports:
    - name: logstash
      port: 5044
      protocol: TCP
      targetPort: 5044

---
apiVersion: v1
kind: Service
metadata:
  name: logstash-headless
spec:
  clusterIP: None
  ports:
    - name: logstash-api
      port: 9600
      protocol: TCP
      targetPort: 9600
