apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
        log stdout format raw
        maxconn 4096

    defaults
        log global
        mode tcp
        timeout connect 5s
        timeout client 50s
        timeout server 50s

    frontend kafka_input
        bind *:9000  # Port lắng nghe từ Kafka
        default_backend vector_aggregators

    backend vector_aggregators
        balance roundrobin
        server vector1 vector-aggregator-0.vector-aggregator.default.svc.cluster.local:9000 check
        server vector2 vector-aggregator-1.vector-aggregator.default.svc.cluster.local:9000 check
        server vector3 vector-aggregator-2.vector-aggregator.default.svc.cluster.local:9000 check
